#!/bin/bash

# SCRIPT DEPLOY BOTPRESS V12 + NEXT.JS LÊN MÁY CHỦ
# Sử dụng script này để deploy lên máy chủ của bạn

echo "🚀 DEPLOY BOTPRESS V12 + NEXT.JS TO SERVER"
echo "=========================================="

# Kiểm tra tham số
if [ $# -eq 0 ]; then
    echo "❌ Vui lòng cung cấp domain của bạn!"
    echo "Cách sử dụng: ./deploy-server.sh your-domain.com"
    echo "Ví dụ: ./deploy-server.sh myserver.com"
    exit 1
fi

DOMAIN=$1
BOTPRESS_PORT=${2:-12000}
NEXTJS_PORT=${3:-12001}

echo "📋 Thông tin deploy:"
echo "   Domain: $DOMAIN"
echo "   Botpress Port: $BOTPRESS_PORT"
echo "   Next.js Port: $NEXTJS_PORT"
echo ""

# Tạo file .env.local cho production
echo "📝 Tạo file .env.local cho production..."
cat > .env.local << EOF
# Botpress V12 Configuration for Production
NEXT_PUBLIC_BOTPRESS_URL=https://$DOMAIN:$BOTPRESS_PORT
NEXT_PUBLIC_NEXTJS_URL=https://$DOMAIN:$NEXTJS_PORT

# Generated by deploy script
DEPLOY_DOMAIN=$DOMAIN
DEPLOY_DATE=$(date)
EOF

echo "✅ File .env.local đã được tạo"

# Kiểm tra Docker
echo "🐳 Kiểm tra Docker..."
if ! command -v docker &> /dev/null; then
    echo "❌ Docker chưa được cài đặt!"
    echo "Vui lòng cài Docker trước: https://docs.docker.com/get-docker/"
    exit 1
fi

# Khởi động Docker daemon nếu cần
if ! docker info &> /dev/null; then
    echo "🔄 Khởi động Docker daemon..."
    sudo systemctl start docker
    sleep 5
fi

# Stop và remove container cũ nếu có
echo "🧹 Dọn dẹp container cũ..."
docker stop botpress-v12-production 2>/dev/null || true
docker rm botpress-v12-production 2>/dev/null || true

# Chạy Botpress V12 container
echo "🚀 Khởi động Botpress V12 container..."
docker run -d \
  --name botpress-v12-production \
  --restart unless-stopped \
  -p $BOTPRESS_PORT:3000 \
  -e EXTERNAL_URL=https://$DOMAIN:$BOTPRESS_PORT \
  -e BP_HOST=0.0.0.0 \
  -e BP_PORT=3000 \
  botpress/server:latest

# Kiểm tra container
sleep 10
if docker ps | grep -q botpress-v12-production; then
    echo "✅ Botpress V12 container đang chạy"
else
    echo "❌ Lỗi khởi động Botpress V12 container"
    docker logs botpress-v12-production
    exit 1
fi

# Cài đặt dependencies
echo "📦 Cài đặt dependencies..."
npm install

# Build Next.js
echo "🔨 Build Next.js..."
npm run build

# Khởi động Next.js
echo "🚀 Khởi động Next.js..."
npm run start -- -p $NEXTJS_PORT -H 0.0.0.0 &
NEXTJS_PID=$!

# Chờ Next.js khởi động
sleep 15

# Kiểm tra services
echo "🔍 Kiểm tra services..."
echo "Botpress V12: https://$DOMAIN:$BOTPRESS_PORT"
echo "Next.js: https://$DOMAIN:$NEXTJS_PORT"

# Test local connections
if curl -f -s http://localhost:$BOTPRESS_PORT > /dev/null; then
    echo "✅ Botpress V12 đang chạy local"
else
    echo "❌ Botpress V12 không phản hồi"
fi

if curl -f -s http://localhost:$NEXTJS_PORT > /dev/null; then
    echo "✅ Next.js đang chạy local"
else
    echo "❌ Next.js không phản hồi"
fi

echo ""
echo "🎉 DEPLOY HOÀN THÀNH!"
echo "========================"
echo "🌐 Truy cập ứng dụng tại: https://$DOMAIN:$NEXTJS_PORT"
echo "🤖 Botpress V12 Admin: https://$DOMAIN:$BOTPRESS_PORT/admin"
echo ""
echo "📋 Luồng sử dụng:"
echo "1. Vào: https://$DOMAIN:$NEXTJS_PORT"
echo "2. Đăng nhập"
echo "3. Admin → AdminBot"
echo "4. Sử dụng Botpress V12!"
echo ""
echo "🔧 Để dừng services:"
echo "   docker stop botpress-v12-production"
echo "   kill $NEXTJS_PID"
echo ""
echo "📝 Log files:"
echo "   Botpress: docker logs botpress-v12-production"
echo "   Next.js PID: $NEXTJS_PID"