name: Deploy to Production Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: --- 1. Connect to Server and Setup ---
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "--- Cleaning up ALL old project directories ---"
            rm -rf /var/www/DuanHpt15T9
            rm -rf /var/www/Hpt202517T9
            
            echo "--- Cloning the new repository with the CORRECT name ---"
            cd /var/www/
            git clone https://github.com/khpt1976-cloud/Hpt202517T9.git Hpt202517T9

      - name: --- 2. Install, Build, and Restart ---
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            echo "--- Navigating to the CORRECT project directory ---"
            cd /var/www/Hpt202517T9/DuanHpt9t9

            echo "--- Installing dependencies ---"
            npm install

            echo "--- Building the application ---"
            npm run build

            echo "--- Restarting the application with the CORRECT name ---"
            pm2 delete all
            pm2 start npm --name "Hpt202517T9" -- start
            pm2 save
            
            echo "--- Deployment successful! ---"
