name: Deploy to Production

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug Secrets
        run: |
          echo "Host Secret (first 5 chars): ${{ secrets.SSH_HOST && secrets.SSH_HOST:0:5 || '' }}"
          echo "Username Secret (first 5 chars): ${{ secrets.SSH_USERNAME && secrets.SSH_USERNAME:0:5 || '' }}"
          echo "Private Key (first 20 chars): ${{ secrets.SSH_PRIVATE_KEY && secrets.SSH_PRIVATE_KEY:0:20 || '' }}"
          echo "Private Key (last 20 chars): ${{ secrets.SSH_PRIVATE_KEY && secrets.SSH_PRIVATE_KEY: -20 || '' }}"

      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Di chuyển đến thư mục dự án
            cd /var/www/Hpt202517T9
            
            # Lấy thông tin mới nhất từ GitHub
            git fetch --all
            
            # Reset cứng về trạng thái của nhánh main trên GitHub
            git reset --hard origin/main
            
            # Cài đặt hoặc cập nhật các gói phụ thuộc
            npm install
            
            # Đồng bộ cơ sở dữ liệu với schema
            npx prisma db push
            
            # Build lại ứng dụng Next.js
            npm run build
            
            # Khởi động lại ứng dụng bằng PM2 một cách mượt mà
            pm2 reload Hpt202517T9
